name: Beta

on:
  push:
    branches:
      - master

jobs:
  beta-build:
    environment: PRODUCTION
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install system dependencies required by some node packages (like node-hid)
      - name: Install build dependencies for native modules
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev libudev-dev

      - name: Retrieve node version from .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Set outputs
        id: vars
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: yarn build
        run: yarn build
        env:
          COMMIT_HASH: ${{ steps.vars.outputs.sha }}

      - name: Zip standalone build folder
        run: zip -r dist/web/standalone_pyrus.zip dist/web/

      - name: 'Save standalone_pyrus.zip to artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: 'standalone_pyrus'
          path: 'dist/web/standalone_pyrus.zip'
